---
- hosts: ipsec

  handlers:
  - include: handlers.yml

  tasks: 
    
  - name: install ipsec tools
    package:
      name: ipsec-tools
      state: latest

  - lineinfile: dest=/etc/ipsec-tools.conf line="flush;" create=yes
    notify:
    - setkey restart

  - lineinfile: dest=/etc/ipsec-tools.conf line="spdflush;" create=yes
    notify:
    - setkey restart

  - template: src=templates/ipsec-tools-manual.conf dest=/etc/ipsec-tools.d/{{item}}.conf
    with_items:
    - "{{groups['ipsec']}}"
    notify:
    - setkey restart
